# Generated by Django 4.1.7 on 2023-03-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_date', models.CharField(max_length=111)),
                ('stock_quantity', models.CharField(max_length=111)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.FileField(upload_to='productdocs/'),
        ),
    ]
