# Generated by Django 4.1.7 on 2023-03-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_stock_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_date',
            field=models.DateField(auto_now=True),
        ),
    ]
