# Generated by Django 4.1.7 on 2023-03-28 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_alter_stock_stock_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='trainertype',
            name='Type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.ttype'),
        ),
    ]
