# Generated by Django 4.1.7 on 2023-03-28 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_ttype_trainertype_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtype_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='trainertype',
            name='Type',
        ),
        migrations.DeleteModel(
            name='TType',
        ),
        migrations.AddField(
            model_name='subtype',
            name='ttype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.trainertype'),
        ),
    ]
