# Generated by Django 4.1.7 on 2023-03-27 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_fitnesstrainer_fitness_vstatus_and_more'),
        ('FitnessTrainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='fitnesstrainer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.fitnesstrainer'),
        ),
        migrations.AlterField(
            model_name='package',
            name='yogatrainer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.yogatrainer'),
        ),
        migrations.AlterField(
            model_name='package',
            name='zumbatrainer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.zumbatrainer'),
        ),
    ]
