# Generated by Django 4.1.7 on 2023-03-27 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessTrainer', '0002_alter_package_fitnesstrainer_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='trainer_photo',
            new_name='package_photo',
        ),
    ]
