# Generated by Django 4.1.7 on 2023-03-28 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessTrainer', '0003_rename_trainer_photo_package_package_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_details', models.TextField(null=True)),
                ('course_video', models.FileField(upload_to='course_videos/')),
                ('course_day', models.CharField(max_length=50)),
                ('uploaded_date', models.DateField(auto_now=True)),
                ('c_status', models.IntegerField(default=0)),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FitnessTrainer.package')),
            ],
        ),
    ]
