# Generated by Django 4.1.7 on 2023-02-27 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_district_place'),
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessTrainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitness_name', models.CharField(max_length=100)),
                ('fitness_contact', models.CharField(max_length=100)),
                ('fitness_email', models.EmailField(max_length=254, unique=True)),
                ('fitness_address', models.TextField(null=True)),
                ('fitness_qualification', models.TextField(null=True)),
                ('fitness_certificate', models.FileField(upload_to='fitnessdocs/')),
                ('fitness_photo', models.FileField(upload_to='fitnessdocs/')),
                ('fitness_password', models.CharField(max_length=100)),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.place')),
                ('trainertype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.trainertype')),
            ],
        ),
    ]
