# Generated by Django 4.1.7 on 2023-02-27 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_district_place'),
        ('Guest', '0002_fitnesstrainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='YogaTrainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yoga_name', models.CharField(max_length=100)),
                ('yoga_contact', models.CharField(max_length=100)),
                ('yoga_email', models.EmailField(max_length=254, unique=True)),
                ('yoga_address', models.TextField(null=True)),
                ('yoga_qualification', models.TextField(null=True)),
                ('yoga_certificate', models.FileField(upload_to='fitnessdocs/')),
                ('yoga_photo', models.FileField(upload_to='fitnessdocs/')),
                ('yoga_password', models.CharField(max_length=100)),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.place')),
                ('trainertype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.trainertype')),
            ],
        ),
    ]
