# Generated by Django 4.1.7 on 2023-02-27 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_district_place'),
        ('Guest', '0003_yogatrainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZumbaTrainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zumba_name', models.CharField(max_length=100)),
                ('zumba_contact', models.CharField(max_length=111)),
                ('zumba_email', models.EmailField(max_length=254, unique=True)),
                ('zumba_address', models.TextField(null=True)),
                ('zumba_qualification', models.TextField(null=True)),
                ('zumba_certificate', models.FileField(upload_to='fitnessdocs/')),
                ('zumba_photo', models.FileField(upload_to='fitnessdocs/')),
                ('zumba_password', models.CharField(max_length=100)),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.place')),
                ('trainertype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.trainertype')),
            ],
        ),
    ]
