# Generated by Django 4.1.7 on 2023-03-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_zumbatrainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnesstrainer',
            name='fitness_vstatus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uregistration',
            name='user_vstatus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='yogatrainer',
            name='yoga_vstatus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zumbatrainer',
            name='zumba_vstatus',
            field=models.IntegerField(default=0),
        ),
    ]
