# Generated by Django 4.1.7 on 2023-03-28 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_subtype_remove_trainertype_type_delete_ttype_and_more'),
        ('Guest', '0005_fitnesstrainer_fitness_vstatus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnesstrainer',
            name='trainertype',
        ),
        migrations.RemoveField(
            model_name='yogatrainer',
            name='trainertype',
        ),
        migrations.RemoveField(
            model_name='zumbatrainer',
            name='trainertype',
        ),
        migrations.AddField(
            model_name='fitnesstrainer',
            name='subtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.subtype'),
        ),
        migrations.AddField(
            model_name='yogatrainer',
            name='subtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.subtype'),
        ),
        migrations.AddField(
            model_name='zumbatrainer',
            name='subtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.subtype'),
        ),
    ]
