# Generated by Django 4.1.7 on 2023-03-29 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessTrainer', '0004_course'),
        ('Guest', '0006_remove_fitnesstrainer_trainertype_and_more'),
        ('User', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.CreateModel(
            name='BookPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(auto_now=True)),
                ('booking_status', models.IntegerField(default=0)),
                ('payment_status', models.IntegerField(default=0)),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FitnessTrainer.package')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.uregistration')),
            ],
        ),
    ]
