# Generated by Django 4.2 on 2023-04-21 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_remove_fitnesstrainer_trainertype_and_more'),
        ('User', '0004_alter_booking_booking_date_bookpackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('from_fitness', models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_fitnss', to='Guest.fitnesstrainer')),
                ('from_user', models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_usr', to='Guest.uregistration')),
                ('from_yoga', models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_yog', to='Guest.yogatrainer')),
                ('from_zumba', models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_zumb', to='Guest.zumbatrainer')),
                ('to_fitness', models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_fitnss', to='Guest.fitnesstrainer')),
                ('to_user', models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_usr', to='Guest.uregistration')),
                ('to_yoga', models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_yog', to='Guest.yogatrainer')),
                ('to_zumba', models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_zumb', to='Guest.zumbatrainer')),
            ],
        ),
    ]
