# Generated by Django 4.2 on 2023-04-25 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_remove_fitnesstrainer_trainertype_and_more'),
        ('User', '0006_remove_chat_from_yoga_remove_chat_from_zumba_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('date', models.DateField(auto_now=True)),
                ('fitnesstrainer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.fitnesstrainer')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.uregistration')),
                ('yogatrainer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.yogatrainer')),
                ('zumbatrainer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.zumbatrainer')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(null=True)),
                ('date', models.DateField(auto_now=True)),
                ('reply', models.TextField(null=True)),
                ('c_status', models.IntegerField(default=0)),
                ('fitnesstrainer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.fitnesstrainer')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.uregistration')),
                ('yogatrainer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.yogatrainer')),
                ('zumbatrainer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.zumbatrainer')),
            ],
        ),
    ]
